version: 2.1

templates:
  tagged-filter: &tagged-filter
    tags:
      only: /[0-9]+(\.[0-9]+)*/

executors:
  ubuntu-builder:
    docker:
      - image: circleci/buildpack-deps:bionic

# define some common commands
# see https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version-21
commands:
  config-path:
    description: "set environment variables and change PATH"
    steps:
    - run:
        name: Configuring PATH
        command: |
          echo 'export PATH=~/repo/venv/bin:${PATH}' >> ${BASH_ENV}

  install-system-deps:
    steps:
      - run:
          name: Install system dependencies
          command: |
            sudo apt update
            sudo apt install -y curl make build-essential libssl-dev libsecp256k1-dev python3 python3-dev python3-distutils python3-venv pkg-config

jobs:
  # install pythom and create an empty python virtualenv
  prepare-system:
    executor: ubuntu-builder
    working_directory: ~/repo

    steps:
      - install-system-deps
      - checkout
      - config-path
      - run:
          name: Create python venv
          command: |
            python3 -m venv venv
            pip install -U pip wheel setuptools

      - persist_to_workspace:
          root: "~"
          paths:
            - repo
  run-flake8:
    executor: ubuntu-builder
    working_directory: ~/repo

    steps:
      - install-system-deps
      - attach_workspace:
          at: '~'
      - config-path
      - restore_cache:
          key: flake8-venv-{{ checksum "constraints.txt" }}
      - run:
          name: Install flake8
          command: |
            pip install flake8 -c constraints.txt
      - save_cache:
          key: flake8-venv-{{ checksum "constraints.txt" }}
          paths:
            - venv
      - run:
          name: Run flake8
          command: |
            flake8 setup.py monitor tests
  install:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - install-system-deps
      - attach_workspace:
          at: '~'
      - config-path

      - restore_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install requirements
          command: |
            pip install -c constraints.txt -r requirements.txt
      - save_cache:
          key: venv-{{ checksum "constraints.txt" }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - run:
          name: Install package
          command: |
            pip install -c constraints.txt .
      - run:
          name: Verify installed packages have compatible dependencies
          command: |
            pip check
      - persist_to_workspace:
          root: "~"
          paths:
            - repo
  run-black:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - install-system-deps
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run black
          command: |
            black --check setup.py monitor tests

  run-mypy:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - install-system-deps
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run mypy
          command: |
            mypy --ignore-missing-imports monitor tests

  run-pytest:
    executor: ubuntu-builder
    working_directory: ~/repo
    steps:
      - install-system-deps
      - attach_workspace:
          at: '~'
      - config-path
      - run:
          name: Run pytest
          command: |
            mkdir -p test-reports
            pytest --junitxml=test-reports/junit.xml --ignore=e2e_tests
      # export test metadata to circleci, see
      # https://circleci.com/docs/2.0/collect-test-data/#pytest
      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports
  build-docker-image:
    executor: ubuntu-builder
    environment:
      LOCAL_IMAGE: tlbc-monitor

    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build docker image
          command: |
            docker build . -t tlbc-monitor
      - run:
          name: Save docker image
          command: |
            mkdir -p ~/images
            docker save --output ~/images/$LOCAL_IMAGE.tar $LOCAL_IMAGE
      - persist_to_workspace:
          root: "~"
          paths:
            - images

  deploy-docker-image:
    executor: ubuntu-builder
    environment:
      LOCAL_IMAGE: tlbc-monitor
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: '~'
      - run:
          name: set DOCKER_REPO
          command: |
            echo ': \"${DOCKER_REPO:=trustlines/tlbc-monitor}\"' >> ${BASH_ENV}
          # this allows us to set DOCKER_REPO from circleci when building in a
          # fork. makes testing easier.
      - run:
          name: Load docker image
          command: |
            echo "Loading $LOCAL_IMAGE to be uploaded to $DOCKER_REPO"
            docker load --input ~/images/$LOCAL_IMAGE.tar
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Upload tagged release
          command: |
            version=$(docker run --rm $LOCAL_IMAGE --version | tr '+' '_')
            echo "Tagging with $DOCKER_REPO:$version"
            docker tag $LOCAL_IMAGE $DOCKER_REPO:$version
            docker push $DOCKER_REPO:$version
      - run:
          name: Upload latest
          command: |
            echo "Tagging with $DOCKER_REPO:latest"
            docker tag $LOCAL_IMAGE $DOCKER_REPO:latest
            docker push $DOCKER_REPO:latest

  end2end:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Pull images
          command: |
            cd e2e_tests; docker-compose pull
      - run:
          name: Build images
          command: |
            cd e2e_tests; docker-compose build
      - run:
          name: "Run end2end tests"
          command: |
            e2e_tests/run-e2e.sh

workflows:
  version: 2
  default:
    jobs:
      - prepare-system:
          filters:
            <<: *tagged-filter
      - run-flake8:
          filters:
            <<: *tagged-filter
          requires:
            - prepare-system
      - install:
          filters:
            <<: *tagged-filter
          requires:
            - prepare-system
      - run-pytest:
          filters:
            <<: *tagged-filter
          requires:
            - install
      - run-mypy:
          filters:
            <<: *tagged-filter
          requires:
            - install
      - run-black:
          filters:
            <<: *tagged-filter
          requires:
            - install
      - build-docker-image:
          filters:
            <<: *tagged-filter
      - deploy-docker-image:
          filters:
            <<: *tagged-filter
            branches:
              only: master
          requires:
            - run-flake8
            - run-black
            - run-pytest
            - run-mypy
            - install
            - build-docker-image
          context: docker-credentials
      - end2end
